name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Dateien nach Strato übertragen
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}

          protocol: sftp
          port: 22

          local-dir: ./
          server-dir: /EchteFruende/

          exclude: |
            **/.git*
            **/.github/**
            **/README.md
            **/.DS_Store