name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Upload per SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.5020498334.ssh.w2.strato.hosting }}
          username: ${{ secrets.su952993 }}
          password: ${{ secrets.kuxxaw-misne8-tepheF }}
          port: 22
          uploads: |
            ./ => /
