name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp \
            -o StrictHostKeyChecking=no \
            -P 22 \
            ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }} <<EOF
          mkdir EchteFruende
          put -r * 
          bye
          EO